spring:
  application:
    name: service
  jackson:
    deserialization:
      accept-float-as-int: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 878044594447-nckmut9kmfrkc0joj96uifo5hk0mraeh.apps.googleusercontent.com
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
server:
  servlet:
    context-path: /esms
  error:
    include-message: always
  forward-headers-strategy: native
  port: 1861

rest-docs:
  host: ddc-java.services
  scheme: https

schedule:
  cron: "-"
  zone: UTC
  stale-code-days: 30

upload:
  applicationHome: true
  directory: uploads
  subdirectoryPattern: "^(.{4})(.{2})(.{2}).*$"
  whitelist:
    - image/bmp
    - image/gif
    - image/jpeg
    - image/pjpeg
    - image/png
    - image/tiff
    - image/heic
  filename:
    format: "%1$s-%2$d.%3$s"
    randomizerLimit: 1000000
    timestamp:
      format: yyyyMMddHHmmssSSS
      timeZone: UTC